name: demo_pixel_assets
description: Retro pixel art sprites for flappy bird
version: 1.0.0

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mss_core:
    path: ../mss_core
  demo_flappy_assets_def:
    path: ../demo_flappy_assets_def
