name: demo_flappy_assets_def
description: Definition for flappy bird visual assets extension
version: 1.0.0

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mss_core:
    path: ../mss_core
